# Generated by Django 3.0.8 on 2020-08-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='horas',
            field=models.IntegerField(),
        ),
    ]
